### ISSUE TITLE
Alles kaputt

### ISSUE THREAD

**Issue by klepek42** [Mastaa12/WIP#1]
# Alles muss nochmal neu gemacht werden

Jetzt sofort!

**Comment by Mastaa12** [comment]
Fuck you, everything OK, Bastard

-------- Originalnachricht --------
Betreff: [WIP] Alles kaputt (#1)
Von: Edgar Klepek
An: Mastaa12/WIP
Cc:

# Alles muss nochmal neu gemacht werden
Jetzt sofort!

---
Reply to this email directly or view it on GitHub:
https://github.com/Mastaa12/WIP/issues/1
